feat(task): add support for installing kubeseal

diff --git a/task b/task
--- a/task
+++ b/task
@@ -125,6 +125,7 @@ function list() {
         printf "$COLUMN" "keepass" "Install KeepassXC."
         printf "$COLUMN" "kind" "Install kind."
         printf "$COLUMN" "kubectl" "Install kubectl."
+        printf "$COLUMN" "kubeseal" "Install kubeseal."
         printf "$COLUMN" "librewolf" "Install LibreWolf."
         printf "$COLUMN" "libreoffice" "Intall LibreOffice."
         printf "$COLUMN" "llm" "Intall LLM cli."
@@ -546,6 +547,23 @@ function install-kubectl() {
         sudo pacman -S --noconfirm kubectl
         sudo pacman -S --noconfirm kubectx
     fi
+}
+
+function install-kubeseal() {
+    # Fetch the latest sealed-secrets version using GitHub API
+    KUBESEAL_VERSION=$(curl -s https://api.github.com/repos/bitnami-labs/sealed-secrets/tags | jq -r '.[0].name' | cut -c 2-)
+
+    # Check if the version was fetched successfully
+    if [ -z "$KUBESEAL_VERSION" ]; then
+        echo "Failed to fetch the latest KUBESEAL_VERSION"
+        exit 1
+    fi
+
+    curl -OL "https://github.com/bitnami-labs/sealed-secrets/releases/download/v${KUBESEAL_VERSION}/kubeseal-${KUBESEAL_VERSION}-linux-amd64.tar.gz"
+    tar -xvzf kubeseal-${KUBESEAL_VERSION}-linux-amd64.tar.gz kubeseal
+    sudo install -m 755 kubeseal /usr/local/bin/kubeseal
+    rm kubeseal-${KUBESEAL_VERSION}-linux-amd64.tar.gz
+    rm kubeseal
 }
 
 function install-kind() {
